version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-local
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: golfhandicap
      MYSQL_USER: admin
      MYSQL_PASSWORD: Snoopy14+
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - golf-network

volumes:
  mysql-data:
    driver: local

networks:
  golf-network:
    driver: bridge
